// partnersData.js
export const partners = [
  { name: "OTG", logo: "/logos/OTG.png", type: "Community" },
  { name: "MOONX", logo: "/logos/MOONX.png", type: "DeFi" },
  { name: "CH90", logo: "/logos/CH90.png", type: "Community" },
  { name: "CRMClick", logo: "/logos/CRMClick.png", type: "Exchange" },
  { name: "BitDoctor", logo: "/logos/BitDoctor.png", type: "DeSci" },
  { name: "BuJingClub", logo: "/logos/BujingClub.png", type: "Community" },
  { name: "CCACC", logo: "/logos/CCACC.png", type: "Incubator" },
  { name: "Chainmedia", logo: "/logos/Chainmedia.png", type: "Media" },
  { name: "Cryptobilis", logo: "/logos/Cryptobilis.png", type: "Community" },
  { name: "DCAI", logo: "/logos/DCAI.png", type: "DeSci" },
  { name: "DTC Group", logo: "/logos/DTC.png", type: "Incubator" },
  { name: "HelloBlockchain", logo: "/logos/HelloBlockchain.png", type: "Event" },
  { name: "Kazepay", logo: "/logos/KazePay.png", type: "Payment" },
  { name: "Lounge69", logo: "/logos/Lounge69.png", type: "Media" },
  { name: "MonashBCC", logo: "/logos/MonashBCC.png", type: "Community" },
  { name: "MORE", logo: "/logos/MoreWeb3Community.png", type: "Community" },
  { name: "PLSLAH", logo: "/logos/PLSLAH.png", type: "Community" },
  { name: "PaddlePop", logo: "/logos/PaddlePop.png", type: "SocialFi" },
  { name: "SBCA", logo: "/logos/SBCA.png", type: "Incubator" },
  { name: "XMUMBCC", logo: "/logos/XMUMBCC.jpg", type: "Community" },
  { name: "YOLO", logo: "/logos/YOLO.png", type: "DeFi" },
  { name: "22Labs", logo: "/logos/224Lab.png", type: "Incubator" },
  { name: "852Web3", logo: "/logos/852Web3.png", type: "Media" },
  { name: "ACCESS", logo: "/logos/ACCESS.png", type: "Association" },
  { name: "ACTIV8", logo: "/logos/ACTIV8.png", type: "Incubator" },
  { name: "APUBCC", logo: "/logos/APUBCC.png", type: "Community" },
  { name: "ARBITECH", logo: "/logos/ARBITECH.png", type: "Project" },
  { name: "Aquavolt", logo: "/logos/Aquavolt.png", type: "Project" },
  { name: "Bit2Travel", logo: "/logos/B2T.png", type: "Travel" },
  { name: "Bitcoin Malaysia", logo: "/logos/bitcoinmalaysia.png", type: "Community" },
  { name: "BinJun Global Labs", logo: "/logos/BJ.png", type: "Incubator" },
  { name: "Blockchain Of The Day", logo: "/logos/BOTD.PNG", type: "Media" },
  { name: "CertiK", logo: "/logos/CertiK.png", type: "Security" },
  { name: "CRM Q", logo: "/logos/CRMQ.png", type: "Trading" },
  { name: "DI", logo: "/logos/DI.png", type: "DePin" },
  { name: "ireadwhatyouwant", logo: "/logos/ireadwhatyouwant.png", type: "Community" },
  { name: "JCI Entrepreneur Metropolitan KL", logo: "/logos/JCI.png", type: "Community" },
  { name: "KiraPay", logo: "/logos/kirapay.png", type: "Payment" },
  { name: "Pudgy Malaysia", logo: "/logos/PudgyMalaysia.png", type: "Community" },
  { name: "Mamak3.0", logo: "/logos/Mamak.png", type: "Community" },
  { name: "OffChain", logo: "/logos/OffChain.png", type: "Community" },
  { name: "Singapore Blockchain Week", logo: "/logos/SBW.png", type: "Event" },
  { name: "Malaysia Blockchain Week", logo: "/logos/MYBW26.png", type: "Event" },
  { name: "Non Ca Phe", logo: "/logos/NonCaPhe.png", type: "F&B" },
  { name: "TAI Community", logo: "/logos/TAI.png", type: "Community" },
  { name: "TankDAO", logo: "/logos/TankDAO.png", type: "Incubator" },
  { name: "TARUMT Blockchain Club", logo: "/logos/TARUMTBCC.png", type: "Community" },
  { name: "SuperTeam Malaysia", logo: "/logos/SuperteamMY.png", type: "Community" },
  { name: "TERRA", logo: "/logos/Terra.png", type: "RWA" },
  { name: "TurboX", logo: "/logos/TurboX.png", type: "Launchpad" },
  { name: "KKAgent", logo: "/logos/KKAgent.png", type: "AI" },
  { name: "FuseSim", logo: "/logos/FuseSim.png", type: "Services" },
  { name: "Hash Community", logo: "/logos/HashCommunity.png", type: "Community" },
  { name: "KTRO Media", logo: "/logos/KTROMEDIA.png", type: "Media" },
  { name: "O2Pay", logo: "/logos/O2Pay.png", type: "Payment" },
  { name: "Sunway Blockchain Club", logo: "/logos/SBCC.png", type: "Community" },
  { name: "MetaEvent", logo: "/logos/MetaEvent.png", type: "Media" },
  { name: "NGX", logo: "/logos/NGX.png", type: "Exchange" },
  { name: "Universe Pro", logo: "/logos/UniversePro.png", type: "DeFi" },
  { name: "UTON", logo: "/logos/UTON.png", type: "Blockchain" },
  { name: "Web3Friday", logo: "/logos/Web3Friday.png", type: "Media" },
  { name: "Web3Vision", logo: "/logos/web3vision.png", type: "Media" },
  { name: "DASH", logo: "/logos/Dash.webp", type: "Payment" },
  { name: "CRM AURUM", logo: "/logos/CRMAURUM.png", type: "Community" },
  { name: "DianDi Finance", logo: "/logos/DianDi.png", type: "Media" },
  { name: "Bright Vision", logo: "/logos/BV.svg", type: "Incubator" },
  { name: "Double Dew", logo: "/logos/DoubleDew.svg", type: "Production" },
  { name: "Chain Catcher", logo: "/logos/ChainCatcher.png", type: "Media" },
  { name: "XOX", logo: "/logos/XOX.png", type: "DeFi" },
  { name: "YiBen Finance", logo: "/logos/YiBen.jpeg", type: "Media" },
  { name: "SWA", logo: "/logos/SWA.png", type: "Services" },
  { name: "Taylors Blockchain Club", logo: "/logos/TaylorsBCC.png", type: "Community" },
  // 以后直接在这里复制粘贴
];
