// partnersData.js
export const partners = [
  { name: "OTG", logo: "/logos/OTG.png", type: "Community" },
  { name: "MOONX", logo: "/logos/MOONX.png", type: "DeFi" },
  { name: "CH90", logo: "/logos/CH90.png", type: "Community" },
  { name: "CRMClick", logo: "/logos/CRMClick.png", type: "Exchange" },
  { name: "BitDoctor", logo: "/logos/BitDoctor.png", type: "DeSci" },
  { name: "BuJingClub", logo: "/logos/BujingClub.png", type: "Community" },
  { name: "CCACC", logo: "/logos/CCACC.png", type: "Incubator" },
  { name: "Chainmedia", logo: "/logos/Chainmedia.png", type: "Media" },
  { name: "Cryptobilis", logo: "/logos/Cryptobilis.png", type: "Community" },
  { name: "DCAI", logo: "/logos/DCAI.png", type: "DeSci" },
  { name: "DTC Group", logo: "/logos/DTC.png", type: "Incubator" },
  { name: "HelloBlockchain", logo: "/logos/HelloBlockchain.png", type: "Event" },
  { name: "Kazepay", logo: "/logos/KazePay.png", type: "Payment" },
  { name: "Lounge69", logo: "/logos/Lounge69.png", type: "Media" },
  { name: "MonashBCC", logo: "/logos/MonashBCC.png", type: "Community" },
  { name: "MORE", logo: "/logos/MoreWeb3Community.png", type: "Community" },
  { name: "PLSLAH", logo: "/logos/PLSLAH.png", type: "Community" },
  { name: "PaddlePop", logo: "/logos/PaddlePop.png", type: "SocialFi" },
  { name: "SBCA", logo: "/logos/SBCA.png", type: "Incubator" },
  { name: "XMUMBCC", logo: "/logos/XMUMBCC.jpg", type: "Community" },
  { name: "YOLO", logo: "/logos/YOLO.png", type: "DeFi" },
  { name: "22Labs", logo: "/logos/224Lab.png", type: "Incubator" },
  { name: "852Web3", logo: "/logos/852Web3.png", type: "Media" },
  { name: "ACCESS", logo: "/logos/ACCESS.png", type: "Association" },
  { name: "ACTIV8", logo: "/logos/ACTIV8.png", type: "Incubator" },
  { name: "APUBCC", logo: "/logos/APUBCC.png", type: "Community" },
  { name: "ARBITECH", logo: "/logos/ARBITECH.png", type: "Project" },
  { name: "Aquavolt", logo: "/logos/Aquavolt.png", type: "Project" },
  { name: "Bit2Travel", logo: "/logos/B2T.png", type: "Travel" },
  { name: "Bitcoin Malaysia", logo: "/logos/bitcoinmalaysia.png", type: "Community" },
  { name: "BinJun Global Labs", logo: "/logos/BJ.png", type: "Incubator" },
  { name: "Blockchain Of The Day", logo: "/logos/BOTD.png", type: "Media" },
  { name: "CertiK", logo: "/logos/CertiK.png", type: "Security" },
  { name: "CRM Q", logo: "/logos/CRMQ.png", type: "Trading" },
  { name: "DI", logo: "/logos/DI.png", type: "DePin" },
  { name: "ireadwhatyouwant", logo: "/logos/ireadwhatyouwant.png", type: "Community" },
  { name: "JCI Entrepreneur Metropolitan KL", logo: "/logos/JCI.png", type: "Community" },
  { name: "KiraPay", logo: "/logos/kirapay.png", type: "Payment" },
  { name: "Pudgy Malaysia", logo: "/logos/PudgyMalaysia.png", type: "Community" },
  // 以后直接在这里复制粘贴
];
