// partnersData.js
export const partners = [
  { name: "OTG", logo: "/logos/OTG.png", type: "Community" },
  { name: "MOONX", logo: "/logos/MOONX.png", type: "DeFi" },
  { name: "CH90", logo: "/logos/CH90.png", type: "Community" },
  { name: "CRMClick", logo: "/logos/CRMClick.png", type: "Exchange" },
  { name: "BitDoctor", logo: "/logos/BitDoctor.png", type: "DeSci" },
  { name: "BuJingClub", logo: "/logos/BujingClub.png", type: "Community" },
  { name: "CCACC", logo: "/logos/CCACC.png", type: "Incubator" },
  { name: "Chainmedia", logo: "/logos/Chainmedia.png", type: "Media" },
  { name: "Cryptobilis", logo: "/logos/Cryptobilis.png", type: "Community" },
  { name: "DCAI", logo: "/logos/DCAI.png", type: "DeSci" },
  { name: "DTC Group", logo: "/logos/DTC.png", type: "Incubator" },
  { name: "HelloBlockchain", logo: "/logos/HelloBlockchain.png", type: "Event" },
  { name: "Kazepay", logo: "/logos/KazePay.png", type: "Payment" },
  { name: "Lounge69", logo: "/logos/Lounge69.png", type: "Media" },
  { name: "MonashBCC", logo: "/logos/MonashBCC.png", type: "Community" },
  { name: "MORE", logo: "/logos/MoreWeb3Community.png", type: "Community" },
  { name: "PLSLAH", logo: "/logos/PLSLAH.png", type: "Community" },
  { name: "PaddlePop", logo: "/logos/PaddlePop.png", type: "SocialFi" },
  { name: "SBCA", logo: "/logos/SBCA.png", type: "Incubator" },
  { name: "XMUMBCC", logo: "/logos/XMUMBCC.jpg", type: "Community" },
  { name: "YOLO", logo: "/logos/YOLO.png", type: "DeFi" },
  // 以后直接在这里复制粘贴
];
